name: bmad-aisg-aiml
version: 2.0.0
short-title: AISG AI/ML Engineering Pack
description: >-
  This expansion pack extends BMad Method with comprehensive AI/ML engineering
  capabilities that is battle-tested in AI Singapore. It provides streamlined workflows and agents,
  optimized for machine learning development and operations in Singapore's AI ecosystem.
author: AISG Innovation Team
slashPrefix: bmadAISG

markdownExploder: true
prd:
  designDoc: docs/aiml-design-document.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/design
  storiesFilePattern: user-story-{n}*.md
architecture:
  architectureFile: docs/aiml-architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/aiml-architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/aiml-architecture/model-architecture.md
  - docs/aiml-architecture/tech-stack.md
  - docs/aiml-architecture/high-level-architecture.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories